# Generated by Django 5.2.7 on 2025-10-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('symbol', models.CharField(max_length=128)),
                ('side', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('limit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('mark_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('delta', models.FloatField()),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remote_order_id', models.BigIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='strategy',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
