# Generated by Django 5.2.7 on 2025-10-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_optionposition_remove_strategy_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='optionposition',
            table='option_position',
        ),
    ]
