# Generated by Django 5.2.7 on 2025-10-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_optionposition_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionposition',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Price at which position was closed', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='optionposition',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='UTC timestamp when position was closed', null=True),
        ),
        migrations.AddField(
            model_name='optionposition',
            name='is_initial_position',
            field=models.BooleanField(default=False, help_text='True if this was one of the initial two positions sold'),
        ),
        migrations.AddField(
            model_name='optionposition',
            name='realized_pnl',
            field=models.DecimalField(decimal_places=8, default=0.0, help_text='Realized PnL when position is closed', max_digits=20),
        ),
        migrations.AddField(
            model_name='optionposition',
            name='strategy_cycle_id',
            field=models.CharField(blank=True, help_text='Monthly cycle identifier (YYYY-MM)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='optionposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
