# Generated by Django 5.2.7 on 2025-10-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_optionposition_close_price_optionposition_closed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPnLTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.CharField(help_text='Monthly cycle identifier (YYYY-MM)', max_length=50)),
                ('underlying', models.CharField(default='BTC', help_text='Underlying asset', max_length=10)),
                ('closed_position_symbol', models.CharField(help_text='Symbol of closed position', max_length=128)),
                ('realized_pnl', models.DecimalField(decimal_places=8, help_text='Realized PnL from closed position', max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=8, help_text='Price at which position was closed', max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=8, help_text='Original entry price', max_digits=20)),
                ('size', models.DecimalField(decimal_places=8, help_text='Position size', max_digits=20)),
                ('closed_at', models.DateTimeField(help_text='UTC timestamp when position was closed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'monthly_pnl_tracker',
                'unique_together': {('cycle_id', 'closed_position_symbol', 'closed_at')},
            },
        ),
    ]
