# Generated by Django 5.2.7 on 2025-10-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_monthlypnltracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialBalanceTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.CharField(help_text='Monthly cycle identifier (YYYY-MM)', max_length=50, unique=True)),
                ('initial_balance_usd', models.DecimalField(decimal_places=8, help_text='Initial USD balance when cycle started', max_digits=20)),
                ('initial_balance_inr', models.DecimalField(decimal_places=2, help_text='Initial INR equivalent balance', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'initial_balance_tracker',
            },
        ),
    ]
