# Generated by Django 5.2.7 on 2025-10-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_initial_balance_tracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyPnLTracker',
        ),
        migrations.RemoveField(
            model_name='optionposition',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='optionposition',
            name='realized_pnl',
        ),
    ]
