# Generated by Django 5.2.7 on 2025-12-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_monthlypnltracker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialbalancetracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CREATED_AT'),
        ),
        migrations.AlterField(
            model_name='initialbalancetracker',
            name='cycle_id',
            field=models.CharField(db_column='CYCLE_ID', help_text='Monthly cycle identifier (YYYY-MM)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='initialbalancetracker',
            name='initial_balance_inr',
            field=models.DecimalField(db_column='INITIAL_BALANCE_INR', decimal_places=2, help_text='Initial INR equivalent balance', max_digits=20),
        ),
        migrations.AlterField(
            model_name='initialbalancetracker',
            name='initial_balance_usd',
            field=models.DecimalField(db_column='INITIAL_BALANCE_USD', decimal_places=8, help_text='Initial USD balance when cycle started', max_digits=20),
        ),
        migrations.AlterField(
            model_name='initialbalancetracker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UPDATED_AT'),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='active',
            field=models.BooleanField(db_column='ACTIVE', default=True),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_column='CLOSED_AT', help_text='UTC timestamp when position was closed', null=True),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CREATED_AT'),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='delta',
            field=models.FloatField(db_column='DELTA'),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='expiry_date',
            field=models.DateField(db_column='EXPIRY_DATE'),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='is_initial_position',
            field=models.BooleanField(db_column='IS_INITIAL_POSITION', default=False, help_text='True if this was one of the initial two positions sold'),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='limit_price',
            field=models.DecimalField(blank=True, db_column='LIMIT_PRICE', decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='mark_price',
            field=models.DecimalField(blank=True, db_column='MARK_PRICE', decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='product_id',
            field=models.IntegerField(db_column='PRODUCT_ID'),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='remote_order_id',
            field=models.BigIntegerField(blank=True, db_column='REMOTE_ORDER_ID', null=True),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='side',
            field=models.CharField(db_column='SIDE', max_length=10),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='size',
            field=models.IntegerField(db_column='SIZE'),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='strategy_cycle_id',
            field=models.CharField(blank=True, db_column='STRATEGY_CYCLE_ID', help_text='Monthly cycle identifier (YYYY-MM)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='strike_price',
            field=models.DecimalField(db_column='STRIKE_PRICE', decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='symbol',
            field=models.CharField(db_column='SYMBOL', max_length=128),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UPDATED_AT'),
        ),
    ]
